# Generated by Django 3.1.7 on 2021-03-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=200)),
                ('bookDetails', models.CharField(max_length=1000)),
                ('bookAmount', models.IntegerField(max_length=200)),
            ],
        ),
    ]
