# Generated by Django 3.1.7 on 2021-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210413_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookAmount',
            field=models.IntegerField(default=0),
        ),
    ]
