# Generated by Django 3.1.7 on 2021-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_books_bookamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookImage',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
