# Generated by Django 3.1.7 on 2021-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210415_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fimage',
            field=models.ImageField(upload_to='uploaded/'),
        ),
    ]
